export const Projects = [
  {
    id: "nexus-tcg",
    path: "/nexus-tcg",
    title: "Nexus TCG",
    product: "",
    client: "Nexus Games",
    year: "2024",
    role: "Founder, CEO, & Game Designer",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/nexus-tcg.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "",
    awards: [],
    skills: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "Tailwind CSS",
      "Material UI",
      "Supabase",
      "GitHub",
      "Vercel",
      "Figma",
      "Tabletop Simulator",
      "Entrepreneurship",
      "Community Management",
    ],
  },
  {
    id: "semble",
    path: "/semble",
    title: "Semble",
    product: "Semble",
    client: "Semble",
    year: "2022-2023",
    role: "Founder & CEO",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/semble.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "hostile-takeover",
    path: "/hostile-takeover",
    title: "Hostile Takeover",
    product: "Call of Duty: Infinite Warfare",
    client: "Activision Blizzard",
    year: "2021",
    role: "Software Engineer",
    problem: "Problem statement.",
    solution: "Solution statement.",
    insight: "Insights.",
    audience: "Audience.",
    description: "A project description.",
    hero: "/images/projects/heroes/hostile-takeover.jpg",
    images: [
      "/images/projects/hostile-takeover/hostile-takeover-1.gif",
      "/images/projects/hostile-takeover/hostile-takeover-2.jpeg", 
      "/images/projects/hostile-takeover/hostile-takeover-3.jpeg", 
      "/images/projects/hostile-takeover/hostile-takeover-4.jpeg", 
    ],
    video: "https://youtu.be/TAEtNeA_WGc",
    awards: [
      {
        award: "Gold",
        category: "Best Use of Gamification",
        show: "Cannes Lions",
        year: "2021"
      },
      {
        award: "Gold",
        category: "Best Use of Gamification",
        show: "Cannes Lions",
        year: "2021"
      }
    ],
    skills: [
      "Next.js", 
      "Node.js", 
      "Typescript", 
      "JavaScript"
    ],
  },
  {
    id: "nordheim",
    path: "/nordheim",
    title: "Nördheim",
    product: "Game design document",
    client: "PUBG (fan project)",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/nordheim.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "chick-houston",
    path: "/chick-houston",
    title: "Chick Houston",
    product: "Lyft",
    client: "Lyft",
    year: "",
    role: "Senior Art Director",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/chick-houston.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/9nMBfSybgEc",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "Adobe Photoshop",
    ],
  },
  {
    id: "",
    path: "auto-tunes",
    title: "Auto-tunes",
    product: "Lyft",
    client: "Lyft",
    year: "",
    role: "Senior Art Director",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/auto-tunes.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/goJswIBghRM",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "swimmers-lounge",
    path: "/swimmers-lounge",
    title: "Swimmer's Lounge",
    product: "Simborgarmärket",
    client: "Simborgarmärket",
    year: "2012",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/swimmers-lounge.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "terminal-tours",
    path: "/terminal-tours",
    title: "Terminal Tours",
    product: "Call of Duty: Infinite Warfare",
    client: "Activision Blizzard",
    year: "2016",
    role: "Senior Art Director",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/terminal-tours.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "",
    awards: [],
    skills: [
      "",
    ],
  },
  {
    id: "team-nvidia",
    path: "/team-nvidia",
    title: "Team NVIDIA",
    product: "NVIDIA Shield",
    client: "NVIDIA",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/team-nvidia.jpg",
    images: [
      "/images/projects/heroes/team-nvidia.jpg",
      "/images/projects/",
    ],
    video: "",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "find-your-party",
    path: "/find-your-party",
    title: "Find Your Party",
    product: "Lyft",
    client: "Lyft",
    year: "",
    role: "Senior Art Director",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/find-your-party.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/xjYnzIKkiM8",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "glow-mode",
    path: "/glow-mode",
    title: "Glow Mode",
    product: "Lyft",
    client: "Lyft",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/glow-mode.jpeg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/mQgmNb2_a84",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "taco-mode",
    path: "/taco-mode",
    title: "Taco Mode",
    product: "",
    client: "",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/taco-mode.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/oQeiBshIpPM",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "tomb",
    path: "/tomb",
    title: "de_tomb",
    product: "",
    client: "",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/tomb.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/o6K2__NjUPA",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
  {
    id: "illustration",
    path: "/illustration",
    title: "Illustration",
    product: "",
    client: "",
    year: "",
    role: "",
    problem: "",
    solution: "",
    insight: "",
    audience: "",
    description: "",
    hero: "/images/projects/heroes/illustration.jpg",
    images: [
      "/images/projects/",
      "/images/projects/",
    ],
    video: "https://youtu.be/o6K2__NjUPA",
    awards: [
      {
        award: "",
        category: "",
        show: "",
        year: ""
      },
    ],
    skills: [
      "",
    ],
  },
]